In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv')

In [5]:
df.head()

,Movie_ID,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime,Movie_Vote,...,Movie_Homepage,Movie_Keywords,Movie_Overview,Movie_Production_House,Movie_Production_Country,Movie_Spoken_Language,Movie_Tagline,Movie_Cast,Movie_Crew,Movie_Director
0,1,Four Rooms,Crime Comedy,en,4000000,22.876230,09-12-1995,4300000,98.0,6.5,...,NaN,hotel new year's eve witch bet hotel room,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,"[{'name': 'Allison Anders', 'gender': 1, 'depa...",Allison Anders
1,2,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695,25-05-1977,775398007,121.0,8.1,...,http://www.starwars.com/films/star-wars-episod...,android galaxy hermit death star lightsaber,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,"[{'name': 'George Lucas', 'gender': 2, 'depart...",George Lucas
2,3,Finding Nemo,Animation Family,en,94000000,85.688789,30-05-2003,940335536,100.0,7.6,...,http://movies.disney.com/finding-nemo,father son relationship harbor underwater fish...,"Nemo, an adventurous young clownfish, is unexp...","[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
3,4,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331,06-07-1994,677945399,142.0,8.2,...,NaN,vietnam veteran hippie mentally disabled runni...,A man with a low IQ has accomplished great thi...,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis
4,5,American Beauty,Drama,en,15000000,80.878605,15-09-1999,356296601,122.0,7.9,...,http://www.dreamworks.com/ab/,male nudity female nudity adultery midlife cri...,"Lester Burnham, a depressed suburban father in...","[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Movie_ID                  4760 non-null   int64
 1   Movie_Title               4760 non-null   object
 2   Movie_Genre               4760 non-null   object
 3   Movie_Language            4760 non-null   object
 4   Movie_Budget              4760 non-null   int64
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object
 7   Movie_Revenue             4760 non-null   int64
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64
 11  Movie_Homepage            1699 non-null   object
 12  Movie_Keywords            4373 non-null   object
 13  Movie_Overview            4757 non-null   object
 14  Movie_Production_House    4760 non-null   object
 15  Movie_Production_Country  4760 non-null   object
 16  Movie_Spoken_Language     4760 non-null   object
 17  Movie_Tagline             3942 non-null   object
 18  Movie_Cast                4733 non-null   object
 19  Movie_Crew                4760 non-null   object
 20  Movie_Director            4738 non-null   object
dtypes: float64(3), int64(4), object(14)
memory usage: 781.1+ KB

In [7]:
df.shape

(4760, 21)

In [8]:
df.columns

Index(['Movie_ID', 'Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime', 'Movie_Vote', 'Movie_Vote_Count',
       'Movie_Homepage', 'Movie_Keywords', 'Movie_Overview',
       'Movie_Production_House', 'Movie_Production_Country',
       'Movie_Spoken_Language', 'Movie_Tagline', 'Movie_Cast', 'Movie_Crew',
       'Movie_Director'],
      dtype='object')

FEATURE

In [9]:
df_features = df[['Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']].fillna('')

In [10]:
df_features.shape

(4760, 5)

In [11]:
df_features

,Movie_Genre,Movie_Keywords,Movie_Tagline,Movie_Cast,Movie_Director
0,Crime Comedy,hotel new year's eve witch bet hotel room,Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,Allison Anders
1,Adventure Action Science Fiction,android galaxy hermit death star lightsaber,"A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,George Lucas
2,Animation Family,father son relationship harbor underwater fish...,"There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,Andrew Stanton
3,Comedy Drama Romance,vietnam veteran hippie mentally disabled runni...,"The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,Robert Zemeckis
4,Drama,male nudity female nudity adultery midlife cri...,Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,Sam Mendes
...,...,...,...,...,...
4755,Horror,,The hot spot where Satan's waitin'.,Lisa Hart Carroll Michael Des Barres Paul Drak...,Pece Dingo
4756,Comedy Family Drama,,It’s better to stand out than to fit in.,Roni Akurati Brighton Sharbino Jason Lee Anjul...,Frank Lotito
4757,Thriller Drama,christian film sex trafficking,She never knew it could happen to her...,Nicole Smolen Kim Baldwin Ariana Stephens Brys...,Jaco Booyens
4758,Family,,,,
4759,Documentary,music actors legendary perfomer classic hollyw...,,Tony Oppedisano,Simon Napier-Bell

In [12]:
x=df_features['Movie_Genre'] + ' ' + df_features['Movie_Keywords'] + ' ' + df_features['Movie_Tagline'] + ' ' + df_features['Movie_Cast'] + ' ' + df_features['Movie_Director']

In [13]:
x

0       Crime Comedy hotel new year's eve witch bet ho...
1       Adventure Action Science Fiction android galax...
2       Animation Family father son relationship harbo...
3       Comedy Drama Romance vietnam veteran hippie me...
4       Drama male nudity female nudity adultery midli...
                              ...
4755    Horror  The hot spot where Satan's waitin'. Li...
4756    Comedy Family Drama  It’s better to stand out ...
4757    Thriller Drama christian film sex trafficking ...
4758                                           Family
4759    Documentary music actors legendary perfomer cl...
Length: 4760, dtype: object

Feature Text Conversions to Tokens

In [14]:
!pip install numpy==1.21.2

ERROR: Ignored the following yanked versions: 2.4.0
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement numpy==1.21.2 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0, 1.25.1, 1.25.2, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0rc1, 2.4.1, 2.4.2, 2.4.3, 2.4.4)
ERROR: No matching distribution found for numpy==1.21.2

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer()

In [17]:
X = tfidf.fit_transform(x)

In [18]:
X.shape

(4760, 17258)

In [19]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 123666 stored elements and shape (4760, 17258)>
  Coords	Values
  (0, 3583)	0.06486754376295062
  (0, 3240)	0.04527089872278055
  (0, 7213)	0.25146675849405775
  (0, 10898)	0.17625708810661284
  (0, 17052)	0.26079573581490934
  (0, 5059)	0.29553419178998613
  (0, 16862)	0.12768803549311025
  (0, 1595)	0.15687561633854538
  (0, 13052)	0.1465525095337543
  (0, 15708)	0.17654247479915475
  (0, 11362)	0.18801785343006192
  (0, 6463)	0.18801785343006192
  (0, 5662)	0.1465525095337543
  (0, 13467)	0.19712637387361423
  (0, 12731)	0.19712637387361423
  (0, 614)	0.07642616241686973
  (0, 11244)	0.08262965296941757
  (0, 9206)	0.15186283580984414
  (0, 1495)	0.19712637387361423
  (0, 7454)	0.14745635785412262
  (0, 7071)	0.19822417598406614
  (0, 5499)	0.11454057510303811
  (0, 3878)	0.11998399582562203
  (0, 11242)	0.07277788238484746
  (0, 15219)	0.09800472886453934
  :	:
  (4757, 3485)	0.199161573117024
  (4757, 1184)	0.18890726729447022
  (4757, 14568)	0.24255077606762876
  (4757, 15508)	0.24255077606762876
  (4757, 5802)	0.24255077606762876
  (4757, 819)	0.27474840155297187
  (4757, 14195)	0.28805858134028367
  (4757, 2227)	0.28805858134028367
  (4757, 7691)	0.28805858134028367
  (4757, 1932)	0.28805858134028367
  (4758, 5238)	1.0
  (4759, 10666)	0.15888268987343043
  (4759, 1490)	0.21197258705292082
  (4759, 15431)	0.19628653185946862
  (4759, 5690)	0.19534291014627303
  (4759, 14051)	0.20084315377640435
  (4759, 4358)	0.18306542312175342
  (4759, 10761)	0.3126617295732147
  (4759, 7130)	0.26419662449963793
  (4759, 3058)	0.2812896191863103
  (4759, 14062)	0.3237911628497312
  (4759, 8902)	0.3040290704566037
  (4759, 205)	0.3237911628497312
  (4759, 11708)	0.33947721804318337
  (4759, 11264)	0.33947721804318337

Similarity Score using Cosine Similarity

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
Similarity_Score = cosine_similarity(X)

In [22]:
Similarity_Score

array([[1.        , 0.01351235, 0.03570468, ..., 0.        , 0.        ,
        0.        ],
       [0.01351235, 1.        , 0.00806674, ..., 0.        , 0.        ,
        0.        ],
       [0.03570468, 0.00806674, 1.        , ..., 0.        , 0.08014876,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.08014876, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [23]:
Similarity_Score.shape

(4760, 4760)

Movie Name as Input from User and Validate for Closest Spelling

In [24]:
Favorite_Movie_Name = input(' Enter your favorite movie name : ')

 Enter your favorite movie name : Titanic

In [25]:
All_Movies_Title_List = df['Movie_Title'].tolist()

In [26]:
import difflib

In [27]:
Movie_Recommendation = difflib.get_close_matches(Favorite_Movie_Name, All_Movies_Title_List)
print(Movie_Recommendation)

['Titanic', 'Trance', 'Maniac']

In [28]:
Close_Match = Movie_Recommendation[0]
print(Close_Match)

Titanic

In [29]:
Index_of_Close_Match_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

256

In [30]:
Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

[(0, np.float64(0.004374333531035219)), (1, np.float64(0.0)), (2, np.float64(0.029627105963890985)), (3, np.float64(0.029431364469359046)), (4, np.float64(0.06114423272641846)), (5, np.float64(0.039683304160885745)), (6, np.float64(0.0)), (7, np.float64(0.0015674440938736275)), (8, np.float64(0.0023696532347936756)), (9, np.float64(0.0)), (10, np.float64(0.006486699078583746)), (11, np.float64(0.0022595159578336094)), (12, np.float64(0.0023300836204128406)), (13, np.float64(0.0)), (14, np.float64(0.0)), (15, np.float64(0.030879578299686187)), (16, np.float64(0.0018186439343890258)), (17, np.float64(0.0)), (18, np.float64(0.007928946144468162)), (19, np.float64(0.023250788764979873)), (20, np.float64(0.05162660237533075)), (21, np.float64(0.00884264064417643)), (22, np.float64(0.016603765519491834)), (23, np.float64(0.0022737977197068216)), (24, np.float64(0.0014251026316195808)), (25, np.float64(0.001804922488955549)), (26, np.float64(0.00213494178323791)), (27, np.float64(0.03586735222811741)), (28, np.float64(0.0)), (29, np.float64(0.0020778603573590885)), (30, np.float64(0.0)), (31, np.float64(0.0020520787306805106)), (32, np.float64(0.0019134560317235383)), (33, np.float64(0.06129604264732634)), (34, np.float64(0.03483684662317486)), (35, np.float64(0.0)), (36, np.float64(0.04807054670939903)), (37, np.float64(0.0)), (38, np.float64(0.006956187745381803)), (39, np.float64(0.0)), (40, np.float64(0.006828028267454018)), (41, np.float64(0.002427921839871012)), (42, np.float64(0.006226103746286324)), (43, np.float64(0.02941378081879961)), (44, np.float64(0.05661110267055516)), (45, np.float64(0.0)), (46, np.float64(0.03334926271263273)), (47, np.float64(0.00540280646327488)), (48, np.float64(0.009111086676461908)), (49, np.float64(0.0)), (50, np.float64(0.006011163686360468)), (51, np.float64(0.02629352143876508)), (52, np.float64(0.03783042263675596)), (53, np.float64(0.0)), (54, np.float64(0.0)), (55, np.float64(0.0)), (56, np.float64(0.0)), (57, np.float64(0.0)), (58, np.float64(0.0)), (59, np.float64(0.0)), (60, np.float64(0.0018665155696952383)), (61, np.float64(0.03305286044774592)), (62, np.float64(0.0024090139669009085)), (63, np.float64(0.0017365563482193511)), (64, np.float64(0.03951170108697503)), (65, np.float64(0.0)), (66, np.float64(0.0021777127049979936)), (67, np.float64(0.0)), (68, np.float64(0.015225091209410837)), (69, np.float64(0.0)), (70, np.float64(0.040888532001355095)), (71, np.float64(0.03144307992477606)), (72, np.float64(0.005903290685234334)), (73, np.float64(0.029893200690170537)), (74, np.float64(0.03560576705270941)), (75, np.float64(0.0)), (76, np.float64(0.0)), (77, np.float64(0.0)), (78, np.float64(0.0)), (79, np.float64(0.024023311724516473)), (80, np.float64(0.0)), (81, np.float64(0.006030909144364157)), (82, np.float64(0.0016557943933514251)), (83, np.float64(0.00616821213597791)), (84, np.float64(0.030643241537529037)), (85, np.float64(0.0424725055428089)), (86, np.float64(0.00523480602103935)), (87, np.float64(0.007982360491561947)), (88, np.float64(0.030833708704343585)), (89, np.float64(0.00686312691099921)), (90, np.float64(0.016352104174793956)), (91, np.float64(0.0)), (92, np.float64(0.001920217537456057)), (93, np.float64(0.0320326096069166)), (94, np.float64(0.03071270494023147)), (95, np.float64(0.017201409449247883)), (96, np.float64(0.06558477591803508)), (97, np.float64(0.0019148265300192992)), (98, np.float64(0.002136567330846184)), (99, np.float64(0.047386401483155385)), (100, np.float64(0.0)), (101, np.float64(0.0)), (102, np.float64(0.0)), (103, np.float64(0.0018898981858567233)), (104, np.float64(0.002195743836370109)), (105, np.float64(0.008200810927177733)), (106, np.float64(0.06069299041150589)), (107, np.float64(0.0024747103429199526)), (108, np.float64(0.0058830764668262306)), (109, np.float64(0.045514192029423486)), (110, np.float64(0.0)), (111, np.float64(0.007681347415118708)), (112, np.float64(0.007960751185829973)), (113, np.float64(0.0017942956784200367)), (114, np.float64(0.0021840441749834735)), (115, np.float64(0.03423264610455312)), (116, np.float64(0.002059350858032851)), (117, np.float64(0.0)), (118, np.float64(0.0)), (119, np.float64(0.002140709294565251)), (120, np.float64(0.05718172266621863)), (121, np.float64(0.002005413691454779)), (122, np.float64(0.034437047923655574)), (123, np.float64(0.0157063766401466)), (124, np.float64(0.022819652831294054)), (125, np.float64(0.0)), (126, np.float64(0.06685903282990628)), (127, np.float64(0.03259788706998717)), (128, np.float64(0.0)), (129, np.float64(0.0015236681998072065)), (130, np.float64(0.0)), (131, np.float64(0.028884798766601848)), (132, np.float64(0.001934469343236031)), (133, np.float64(0.0)), (134, np.float64(0.0)), (135, np.float64(0.01670777328296252)), (136, np.float64(0.002014953870016527)), (137, np.float64(0.006266823261805402)), (138, np.float64(0.022559224771183477)), (139, np.float64(0.0068293958021896995)), (140, np.float64(0.0020439134088768283)), (141, np.float64(0.051817286044729474)), (142, np.float64(0.050908828034154086)), (143, np.float64(0.006385306794237737)), (144, np.float64(0.049577350563376296)), (145, np.float64(0.012410383018406763)), (146, np.float64(0.0)), (147, np.float64(0.00715393605906402)), (148, np.float64(0.005523670028620002)), (149, np.float64(0.03267271284762101)), (150, np.float64(0.0)), (151, np.float64(0.0)), (152, np.float64(0.0)), (153, np.float64(0.0)), (154, np.float64(0.0020481252913717336)), (155, np.float64(0.0)), (156, np.float64(0.0017725376162875245)), (157, np.float64(0.03861208957481922)), (158, np.float64(0.001957237365596081)), (159, np.float64(0.001707718257990467)), (160, np.float64(0.028686390213300307)), (161, np.float64(0.001961268875098639)), (162, np.float64(0.006685501347064365)), (163, np.float64(0.029124513057993337)), (164, np.float64(0.002076231201031179)), (165, np.float64(0.0018862279208302537)), (166, np.float64(0.040318247191175424)), (167, np.float64(0.0021079102676259654)), (168, np.float64(0.018390172107910337)), (169, np.float64(0.0021437721045291687)), (170, np.float64(0.005515114717250974)), (171, np.float64(0.0)), (172, np.float64(0.008295117290488919)), (173, np.float64(0.0086662313321806)), (174, np.float64(0.0021552390504522116)), (175, np.float64(0.001842464090380438)), (176, np.float64(0.00224206344554407)), (177, np.float64(0.0)), (178, np.float64(0.0022953472779962117)), (179, np.float64(0.0)), (180, np.float64(0.006504507562595701)), (181, np.float64(0.012092821701321178)), (182, np.float64(0.03374561157007501)), (183, np.float64(0.0020011167931959888)), (184, np.float64(0.01664666109675624)), (185, np.float64(0.0)), (186, np.float64(0.0)), (187, np.float64(0.0)), (188, np.float64(0.0)), (189, np.float64(0.03240900606395247)), (190, np.float64(0.0070563587974498305)), (191, np.float64(0.0)), (192, np.float64(0.07005901857926851)), (193, np.float64(0.002306975551281985)), (194, np.float64(0.0017506465730881375)), (195, np.float64(0.04219540023652584)), (196, np.float64(0.0018327244174053921)), (197, np.float64(0.0020602371913501535)), (198, np.float64(0.06572225114594521)), (199, np.float64(0.007539707684377056)), (200, np.float64(0.0019280013396426234)), (201, np.float64(0.00635068305950327)), (202, np.float64(0.0014317479609334191)), (203, np.float64(0.002064569076292331)), (204, np.float64(0.03497603590001751)), (205, np.float64(0.04061939150990062)), (206, np.float64(0.008771504585078364)), (207, np.float64(0.006875283186042717)), (208, np.float64(0.0023165156022121364)), (209, np.float64(0.02590950754049507)), (210, np.float64(0.008911795027451586)), (211, np.float64(0.06057247294505373)), (212, np.float64(0.02429323038903414)), (213, np.float64(0.06455435464042222)), (214, np.float64(0.0)), (215, np.float64(0.0021436230519669866)), (216, np.float64(0.03453803634122963)), (217, np.float64(0.039587299660039564)), (218, np.float64(0.0019920367471821603)), (219, np.float64(0.0)), (220, np.float64(0.0)), (221, np.float64(0.0020745819118045583)), (222, np.float64(0.0019204824161691907)), (223, np.float64(0.0)), (224, np.float64(0.006326524732860605)), (225, np.float64(0.0)), (226, np.float64(0.0021816697860929006)), (227, np.float64(0.0023319021832630743)), (228, np.float64(0.0016525222643583915)), (229, np.float64(0.0020342350663151835)), (230, np.float64(0.0)), (231, np.float64(0.0)), (232, np.float64(0.0)), (233, np.float64(0.0)), (234, np.float64(0.03966081640421785)), (235, np.float64(0.002462802037974031)), (236, np.float64(0.007767105603748939)), (237, np.float64(0.084105633780751)), (238, np.float64(0.024578721779399817)), (239, np.float64(0.0)), (240, np.float64(0.028968272443195782)), (241, np.float64(0.0)), (242, np.float64(0.001889157072841571)), (243, np.float64(0.0015361726429603314)), (244, np.float64(0.03657120562028371)), (245, np.float64(0.0)), (246, np.float64(0.0023204678208535363)), (247, np.float64(0.002157421826453311)), (248, np.float64(0.02895292080911311)), (249, np.float64(0.001913575702049496)), (250, np.float64(0.0)), (251, np.float64(0.007087288157212569)), (252, np.float64(0.02411747371062153)), (253, np.float64(0.00238559385500088)), (254, np.float64(0.00911402137382691)), (255, np.float64(0.002284883466441152)), (256, np.float64(1.0)), (257, np.float64(0.0)), (258, np.float64(0.0)), (259, np.float64(0.0)), (260, np.float64(0.0)), (261, np.float64(0.0)), (262, np.float64(0.0022922250365797017)), (263, np.float64(0.0)), (264, np.float64(0.0)), (265, np.float64(0.03460980250278607)), (266, np.float64(0.020949539818812528)), (267, np.float64(0.0018490930145368455)), (268, np.float64(0.0019461018426274014)), (269, np.float64(0.0018722768880971446)), (270, np.float64(0.0774905061557222)), (271, np.float64(0.001672216025023621)), (272, np.float64(0.047161792003036926)), (273, np.float64(0.0)), (274, np.float64(0.009494363349839583)), (275, np.float64(0.0)), (276, np.float64(0.0077966509792701)), (277, np.float64(0.03035119942227134)), (278, np.float64(0.001879250091384009)), (279, np.float64(0.002042669285215346)), (280, np.float64(0.008247277772907584)), (281, np.float64(0.009334744215567304)), (282, np.float64(0.008146158715441568)), (283, np.float64(0.001596769741290717)), (284, np.float64(0.0)), (285, np.float64(0.07174900026306329)), (286, np.float64(0.0018723888236476644)), (287, np.float64(0.007758860197166158)), (288, np.float64(0.0)), (289, np.float64(0.0)), (290, np.float64(0.0)), (291, np.float64(0.03407546376677702)), (292, np.float64(0.0021169799467284692)), (293, np.float64(0.03213861099018185)), (294, np.float64(0.02491910869431929)), (295, np.float64(0.0)), (296, np.float64(0.0016353391241968965)), (297, np.float64(0.0)), (298, np.float64(0.0)), (299, np.float64(0.0)), (300, np.float64(0.0)), (301, np.float64(0.0)), (302, np.float64(0.0)), (303, np.float64(0.0)), (304, np.float64(0.06331955869386356)), (305, np.float64(0.0)), (306, np.float64(0.0)), (307, np.float64(0.03570265592220216)), (308, np.float64(0.002439947773800348)), (309, np.float64(0.028814722012587914)), (310, np.float64(0.0)), (311, np.float64(0.005713252808949595)), (312, np.float64(0.0)), (313, np.float64(0.0)), (314, np.float64(0.0)), (315, np.float64(0.0)), (316, np.float64(0.0)), (317, np.float64(0.033864721927953964)), (318, np.float64(0.002384526602250268)), (319, np.float64(0.0)), (320, np.float64(0.0)), (321, np.float64(0.0)), (322, np.float64(0.0)), (323, np.float64(0.0)), (324, np.float64(0.0020110847549937656)), (325, np.float64(0.036546586905490654)), (326, np.float64(0.0026721519884709654)), (327, np.float64(0.015000732156365822)), (328, np.float64(0.0)), (329, np.float64(0.0021166793185114024)), (330, np.float64(0.0015076522189410363)), (331, np.float64(0.0)), (332, np.float64(0.0)), (333, np.float64(0.005414205029543299)), (334, np.float64(0.005477161204267251)), (335, np.float64(0.02893324450558005)), (336, np.float64(0.0)), (337, np.float64(0.0)), (338, np.float64(0.0)), (339, np.float64(0.0)), (340, np.float64(0.0)), (341, np.float64(0.0)), (342, np.float64(0.03629116852548753)), (343, np.float64(0.0021985157917901853)), (344, np.float64(0.0)), (345, np.float64(0.005899390649521431)), (346, np.float64(0.018784367416278085)), (347, np.float64(0.0)), (348, np.float64(0.00215996465004779)), (349, np.float64(0.002116233900920805)), (350, np.float64(0.0023754231692989253)), (351, np.float64(0.001664707632273468)), (352, np.float64(0.0)), (353, np.float64(0.0022160647939171094)), (354, np.float64(0.0)), (355, np.float64(0.002011982954628036)), (356, np.float64(0.002081284313034047)), (357, np.float64(0.0018829029463707592)), (358, np.float64(0.0021221186354205336)), (359, np.float64(0.0020024054026334215)), (360, np.float64(0.005775725451277263)), (361, np.float64(0.0)), (362, np.float64(0.0)), (363, np.float64(0.0)), (364, np.float64(0.020732025967572836)), (365, np.float64(0.018569777938612288)), (366, np.float64(0.0)), (367, np.float64(0.04020408565923937)), (368, np.float64(0.007306380521987337)), (369, np.float64(0.004658477890877434)), (370, np.float64(0.008255503566394337)), (371, np.float64(0.0024010162978248544)), (372, np.float64(0.00203303723990098)), (373, np.float64(0.00206789906985092)), (374, np.float64(0.0021527878164014605)), (375, np.float64(0.030929860669102256)), (376, np.float64(0.0)), (377, np.float64(0.0344944636587228)), (378, np.float64(0.0021913138538704005)), (379, np.float64(0.0)), (380, np.float64(0.0)), (381, np.float64(0.0)), (382, np.float64(0.042385100757096096)), (383, np.float64(0.0)), (384, np.float64(0.0)), (385, np.float64(0.00673827009106517)), (386, np.float64(0.0)), (387, np.float64(0.002057853867637829)), (388, np.float64(0.03160449878274767)), (389, np.float64(0.0)), (390, np.float64(0.0)), (391, np.float64(0.0)), (392, np.float64(0.0)), (393, np.float64(0.0)), (394, np.float64(0.0)), (395, np.float64(0.035919197640393044)), (396, np.float64(0.024674635626141077)), (397, np.float64(0.057230574724035484)), (398, np.float64(0.0)), (399, np.float64(0.00202182265972189)), (400, np.float64(0.0021619352793527573)), (401, np.float64(0.03636568397049767)), (402, np.float64(0.0026599519394122843)), (403, np.float64(0.0018494163537428456)), (404, np.float64(0.0)), (405, np.float64(0.0)), (406, np.float64(0.002226189370146207)), (407, np.float64(0.0017507387952530378)), (408, np.float64(0.03740741449591359)), (409, np.float64(0.0)), (410, np.float64(0.002029976217141042)), (411, np.float64(0.0)), (412, np.float64(0.07848834210133943)), (413, np.float64(0.0)), (414, np.float64(0.0)), (415, np.float64(0.030922314531950792)), (416, np.float64(0.0019994976388235147)), (417, np.float64(0.03284762139916556)), (418, np.float64(0.07264681557098071)), (419, np.float64(0.002457471314604704)), (420, np.float64(0.03743775784777107)), (421, np.float64(0.0)), (422, np.float64(0.06489162993182493)), (423, np.float64(0.0)), (424, np.float64(0.0)), (425, np.float64(0.0332121684915852)), (426, np.float64(0.01564088262362854)), (427, np.float64(0.030019234609617165)), (428, np.float64(0.0019699569635973787)), (429, np.float64(0.02691009115634036)), (430, np.float64(0.0023485130854765056)), (431, np.float64(0.0025732495492337263)), (432, np.float64(0.001856238749498788)), (433, np.float64(0.0017848372884670693)), (434, np.float64(0.007822793791890659)), (435, np.float64(0.034526898179158355)), (436, np.float64(0.0024412487376752182)), (437, np.float64(0.0020703887260130624)), (438, np.float64(0.02558528395530564)), (439, np.float64(0.0)), (440, np.float64(0.038219921546274904)), (441, np.float64(0.0018031021856338698)), (442, np.float64(0.001809229611701107)), (443, np.float64(0.03872257908920673)), (444, np.float64(0.0024311889871689463)), (445, np.float64(0.059376494582605285)), (446, np.float64(0.002128527382340559)), (447, np.float64(0.0410837426656622)), (448, np.float64(0.0025185306266743476)), (449, np.float64(0.001973397460866283)), (450, np.float64(0.009073365262752148)), (451, np.float64(0.0)), (452, np.float64(0.0016433901394031628)), (453, np.float64(0.0016684801407186951)), (454, np.float64(0.0)), (455, np.float64(0.0015483295250158043)), (456, np.float64(0.040975622948447296)), (457, np.float64(0.0020026331218343414)), (458, np.float64(0.009226483706360556)), (459, np.float64(0.0)), (460, np.float64(0.03571399309907643)), (461, np.float64(0.00720823610345926)), (462, np.float64(0.0)), (463, np.float64(0.029698838067727055)), (464, np.float64(0.002156769443499854)), (465, np.float64(0.0019920355504257892)), (466, np.float64(0.0021571944186727448)), (467, np.float64(0.0)), (468, np.float64(0.0)), (469, np.float64(0.0)), (470, np.float64(0.0353094002889586)), (471, np.float64(0.002037643966112769)), (472, np.float64(0.0022463435238944964)), (473, np.float64(0.001974045071748563)), (474, np.float64(0.006395838000823164)), (475, np.float64(0.008087476952766392)), (476, np.float64(0.002395161698124296)), (477, np.float64(0.0)), (478, np.float64(0.002469431178230311)), (479, np.float64(0.008259133839471591)), (480, np.float64(0.0019146731717494007)), (481, np.float64(0.04302786585038039)), (482, np.float64(0.03781369219772001)), (483, np.float64(0.027110548922848757)), (484, np.float64(0.0)), (485, np.float64(0.008861370033252516)), (486, np.float64(0.04425396842219426)), (487, np.float64(0.03410426803629753)), (488, np.float64(0.0021105125479185835)), (489, np.float64(0.002610180994351372)), (490, np.float64(0.026961277343460117)), (491, np.float64(0.0)), (492, np.float64(0.0)), (493, np.float64(0.0023166856451938066)), (494, np.float64(0.006114870421927042)), (495, np.float64(0.0019298689092623667)), (496, np.float64(0.0018628553961354969)), (497, np.float64(0.005416693184405435)), (498, np.float64(0.0)), (499, np.float64(0.02963054399535861)), (500, np.float64(0.06696735863482084)), (501, np.float64(0.005465905685634079)), (502, np.float64(0.008656615652600105)), (503, np.float64(0.005921154236583665)), (504, np.float64(0.0021951554038545052)), (505, np.float64(0.0020728282991091893)), (506, np.float64(0.03823036264704599)), (507, np.float64(0.0020488077586621827)), (508, np.float64(0.002508891648772856)), (509, np.float64(0.0022376522732576506)), (510, np.float64(0.0017441318646429962)), (511, np.float64(0.0)), (512, np.float64(0.0)), (513, np.float64(0.0)), (514, np.float64(0.0)), (515, np.float64(0.06800639114182719)), (516, np.float64(0.0)), (517, np.float64(0.06840584740878768)), (518, np.float64(0.0025579866197150036)), (519, np.float64(0.0019265630357518397)), (520, np.float64(0.0)), (521, np.float64(0.0)), (522, np.float64(0.0021180372515933314)), (523, np.float64(0.0)), (524, np.float64(0.05942325330295233)), (525, np.float64(0.0)), (526, np.float64(0.0027437897747098158)), (527, np.float64(0.0017273880923691619)), (528, np.float64(0.0)), (529, np.float64(0.0)), (530, np.float64(0.005991838576568722)), (531, np.float64(0.0)), (532, np.float64(0.005652217818795581)), (533, np.float64(0.009300431265358363)), (534, np.float64(0.008166887021243888)), (535, np.float64(0.0)), (536, np.float64(0.0)), (537, np.float64(0.0)), (538, np.float64(0.0)), (539, np.float64(0.0059563669463037145)), (540, np.float64(0.0)), (541, np.float64(0.12319762487733692)), (542, np.float64(0.005798533110000569)), (543, np.float64(0.04120807947165839)), (544, np.float64(0.008391202589300092)), (545, np.float64(0.0)), (546, np.float64(0.0)), (547, np.float64(0.006971585083727751)), (548, np.float64(0.0)), (549, np.float64(0.0)), (550, np.float64(0.0)), (551, np.float64(0.028276698238385214)), (552, np.float64(0.0)), (553, np.float64(0.0)), (554, np.float64(0.0)), (555, np.float64(0.0)), (556, np.float64(0.0)), (557, np.float64(0.0)), (558, np.float64(0.007624898982331962)), (559, np.float64(0.0)), (560, np.float64(0.006105337338027847)), (561, np.float64(0.0)), (562, np.float64(0.05006069741594735)), (563, np.float64(0.0019675272354599785)), (564, np.float64(0.0022859376073844783)), (565, np.float64(0.029231320664952834)), (566, np.float64(0.04651601682603873)), (567, np.float64(0.

In [31]:
len(Recommendation_Score)

4760

All Movies Sort Based on Recommendation Score wrt Favourite Movie

In [32]:
Sorted_Similar_Movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)
print(Sorted_Similar_Movies)

[(256, np.float64(1.0)), (1647, np.float64(0.16928550948380916)), (1080, np.float64(0.16294958089491904)), (1562, np.float64(0.15031127357002316)), (3005, np.float64(0.14425171534446568)), (940, np.float64(0.1425708333427374)), (1226, np.float64(0.1363506276486921)), (2269, np.float64(0.136230871816428)), (1295, np.float64(0.13169891222180657)), (3956, np.float64(0.12591503772020757)), (541, np.float64(0.12319762487733692)), (1964, np.float64(0.12220110779486909)), (2845, np.float64(0.1214508864436153)), (3092, np.float64(0.12089627069158188)), (705, np.float64(0.1192518624084536)), (1281, np.float64(0.11844510935932337)), (4288, np.float64(0.11808148844105258)), (1553, np.float64(0.11645618158131679)), (2585, np.float64(0.11564979892037486)), (3614, np.float64(0.11528636816009594)), (1454, np.float64(0.11410737861746877)), (2981, np.float64(0.11272006071826503)), (3297, np.float64(0.11198538394153806)), (2624, np.float64(0.11013953054928374)), (1802, np.float64(0.10724988146950976)), (1484, np.float64(0.10647399056129336)), (2104, np.float64(0.10605341917403854)), (1582, np.float64(0.10558047761394923)), (1970, np.float64(0.1054489441867868)), (2250, np.float64(0.10516331075249889)), (4286, np.float64(0.10157416294190584)), (3179, np.float64(0.1011165978837571)), (3149, np.float64(0.10085603153650119)), (3085, np.float64(0.09988855839501072)), (1505, np.float64(0.09740303840044207)), (2340, np.float64(0.09631001703777142)), (3318, np.float64(0.0962039366606653)), (1255, np.float64(0.09563869087323365)), (1101, np.float64(0.0954333190284544)), (1314, np.float64(0.09508973944401528)), (810, np.float64(0.09502290080546422)), (2617, np.float64(0.09411071991129297)), (4304, np.float64(0.09324028308972869)), (2323, np.float64(0.09083445600056439)), (1919, np.float64(0.09081471755039465)), (1353, np.float64(0.0903038803344022)), (1480, np.float64(0.09027284052543222)), (1083, np.float64(0.08985160331053259)), (856, np.float64(0.08984720578900783)), (3331, np.float64(0.08980445581247588)), (2429, np.float64(0.08943530662829054)), (1394, np.float64(0.08917915131633375)), (1974, np.float64(0.08875762661572106)), (3328, np.float64(0.08796620081562107)), (3083, np.float64(0.08728023461197622)), (636, np.float64(0.08721441508699901)), (709, np.float64(0.0867396056413558)), (1614, np.float64(0.08558396772677185)), (892, np.float64(0.08531014483020663)), (2968, np.float64(0.08446101818273757)), (4322, np.float64(0.08438697342947582)), (1829, np.float64(0.08422748225692915)), (237, np.float64(0.084105633780751)), (2689, np.float64(0.08407879779412451)), (1074, np.float64(0.08372244346919863)), (1944, np.float64(0.08066459629505676)), (4523, np.float64(0.08049392782315395)), (3377, np.float64(0.08036772481676806)), (901, np.float64(0.07957411004959102)), (412, np.float64(0.07848834210133943)), (2835, np.float64(0.07838972441327985)), (3659, np.float64(0.07837599821383862)), (4598, np.float64(0.07790679016287393)), (270, np.float64(0.0774905061557222)), (1156, np.float64(0.07707593397440575)), (3857, np.float64(0.07703718331972823)), (4498, np.float64(0.07694515365825656)), (1018, np.float64(0.07678208328370541)), (1243, np.float64(0.07565198385814084)), (3101, np.float64(0.0751344033539506)), (4263, np.float64(0.07490377749663661)), (1003, np.float64(0.07479678651562251)), (2978, np.float64(0.0746793227387888)), (1493, np.float64(0.07460048597786889)), (2949, np.float64(0.07410897377178755)), (2356, np.float64(0.07387009350354055)), (1983, np.float64(0.0738018252213547)), (2578, np.float64(0.07334991344664583)), (2762, np.float64(0.07309110054501815)), (4337, np.float64(0.07308885404775473)), (893, np.float64(0.07268898884375448)), (418, np.float64(0.07264681557098071)), (3283, np.float64(0.0725622402319868)), (3415, np.float64(0.07227291100921357)), (3285, np.float64(0.0722245234384752)), (3073, np.float64(0.07219820722168126)), (1544, np.float64(0.07213400700883034)), (873, np.float64(0.07193640154891962)), (285, np.float64(0.07174900026306329)), (3528, np.float64(0.07127978743308702)), (3225, np.float64(0.07107589615310583)), (1479, np.float64(0.07104477736542843)), (192, np.float64(0.07005901857926851)), (1633, np.float64(0.06992124806769529)), (1362, np.float64(0.06977184920492548)), (3333, np.float64(0.0695857068603318)), (4688, np.float64(0.0694328002300732)), (2746, np.float64(0.06914751422749313)), (2228, np.float64(0.06893595740536324)), (930, np.float64(0.06875333070329206)), (4148, np.float64(0.06841155042030864)), (517, np.float64(0.06840584740878768)), (4125, np.float64(0.06836753077264358)), (1361, np.float64(0.06823853658314999)), (1248, np.float64(0.06808360789081512)), (1504, np.float64(0.06802251014992242)), (515, np.float64(0.06800639114182719)), (2353, np.float64(0.06777259977194224)), (1103, np.float64(0.06744939855534508)), (3915, np.float64(0.06733045721537542)), (2322, np.float64(0.06726855505011352)), (1261, np.float64(0.06715375557482353)), (500, np.float64(0.06696735863482084)), (126, np.float64(0.06685903282990628)), (3650, np.float64(0.06669816564833608)), (2131, np.float64(0.0666294240263708)), (1595, np.float64(0.0666162802351175)), (2029, np.float64(0.06646199223284122)), (3289, np.float64(0.06638349884647142)), (1173, np.float64(0.06630163162746802)), (2919, np.float64(0.06615373685287718)), (3637, np.float64(0.06597919188099657)), (1153, np.float64(0.06582998747945368)), (198, np.float64(0.06572225114594521)), (1533, np.float64(0.065706958587428)), (96, np.float64(0.06558477591803508)), (1175, np.float64(0.06537125793165269)), (1824, np.float64(0.06518275010368885)), (422, np.float64(0.06489162993182493)), (900, np.float64(0.06485000576322525)), (1469, np.float64(0.06479930522787661)), (2766, np.float64(0.06466654658350902)), (4628, np.float64(0.06460604698033082)), (708, np.float64(0.06457958633708724)), (3147, np.float64(0.0645699279793936)), (213, np.float64(0.06455435464042222)), (2297, np.float64(0.06452135551666602)), (1536, np.float64(0.06432188230515784)), (2759, np.float64(0.06414110724367961)), (769, np.float64(0.06392736120019152)), (3533, np.float64(0.06381581260783306)), (3389, np.float64(0.06379040476420803)), (2347, np.float64(0.0637599554344878)), (3833, np.float64(0.06356620859333188)), (1026, np.float64(0.06356237058097927)), (1068, np.float64(0.06351551169086198)), (304, np.float64(0.06331955869386356)), (2100, np.float64(0.06329646642715059)), (4299, np.float64(0.06323440879004061)), (4407, np.float64(0.06302089908750144)), (959, np.float64(0.06291653974276094)), (805, np.float64(0.06288801966555949)), (2480, np.float64(0.06205538782006399)), (4063, np.float64(0.06199600075472453)), (2822, np.float64(0.06193208230907102)), (3498, np.float64(0.06189015643405373)), (2747, np.float64(0.06172797218008003)), (1272, np.float64(0.06167315169104448)), (4321, np.float64(0.06166896108881815)), (1130, np.float64(0.06133479321313646)), (733, np.float64(0.06131195432360987)), (33, np.float64(0.06129604264732634)), (2598, np.float64(0.061284538076428766)), (1468, np.float64(0.061211357682898634)), (4, np.float64(0.06114423272641846)), (1784, np.float64(0.061000284825325664)), (3433, np.float64(0.06099198631835902)), (694, np.float64(0.06091292198450466)), (2899, np.float64(0.0608914338782642)), (2548, np.float64(0.060822864268083504)), (106, np.float64(0.06069299041150589)), (3243, np.float64(0.06066830669179137)), (2276, np.float64(0.060575721844493766)), (211, np.float64(0.06057247294505373)), (773, np.float64(0.06055145194634374)), (655, np.float64(0.06048904192018803)), (4583, np.float64(0.060426513925912875)), (703, np.float64(0.06040919873591194)), (2465, np.float64(0.06032639841835322)), (958, np.float64(0.06016545347149373)), (3642, np.float64(0.06012375082687636)), (1052, np.float64(0.05996759855769511)), (638, np.float64(0.059700931759478326)), (1754, np.float64(0.059444007457993706)), (524, np.float64(0.05942325330295233)), (1532, np.float64(0.059415274978607)), (445, np.float64(0.059376494582605285)), (4022, np.float64(0.05932993364939369)), (4359, np.float64(0.059137945781192004)), (3853, np.float64(0.059102543479296)), (2965, np.float64(0.05866351195715226)), (4159, np.float64(0.058662160511975564)), (3580, np.float64(0.05859529562098757)), (1827, np.float64(0.05857515652799571)), (3336, np.float64(0.058302888968068116)), (2591, np.float64(0.05811343531863659)), (1402, np.float64(0.05808793262794887)), (4433, np.float64(0.057883669228685514)), (3559, np.float64(0.057882384288745696)), (1202, np.float64(0.05768523701283369)), (816, np.float64(0.05767554637409045)), (2801, np.float64(0.057626510949931764)), (3380, np.float64(0.05750089215048221)), (397, np.float64(0.057230574724035484)), (120, np.float64(0.05718172266621863)), (4153, np.float64(0.05704014077064438)), (695, np.float64(0.05697260493308627)), (2626, np.float64(0.056970825719507685)), (1492, np.float64(0.056964518734896774)), (2760, np.float64(0.056754605376884)), (4375, np.float64(0.05662489536565918)), (44, np.float64(0.05661110267055516)), (1956, np.float64(0.056408780309931766)), (2142, np.float64(0.056191059719220796)), (688, np.float64(0.05561096027777178)), (3315, np.float64(0.05535879895300949)), (2056, np.float64(0.05535644039819511)), (3200, np.float64(0.0550375496254468)), (3344, np.float64(0.05501126377476049)), (2824, np.float64(0.05499134714523268)), (2227, np.float64(0.054697370376824296)), (951, np.float64(0.0546825618088638)), (3394, np.float64(0.05458764001629884)), (1756, np.float64(0.05449274595217303)), (1329, np.float64(0.05434709422555681)), (1559, np.float64(0.05417204148159211)), (3856, np.float64(0.05417078679939422)), (1367, np.float64(0.05409332200727302)), (4449, np.float64(0.05407060961343731)), (3279, np.float64(0.05363546054137725)), (1779, np.float64(0.05344706186152989)), (786, np.float64(0.0534397797887238)), (1455, np.float64(0.05319810134518443)), (4059, np.float64(0.05319035809504746)), (2622, np.float64(0.053105028636084295)), (1167, np.float64(0.052607538515511025)), (742, np.float64(0.05207129409155327)), (2699, np.float64(0.05202819487408788)), (3716, np.float64(0.05194640925648018)), (3071, np.float64(0.0518860889775782)), (141, np.float64(0.051817286044729474)), (2661, np.float64(0.05181197525602093)), (3142, np.float64(0.05168637005165254)), (20, np.float64(0.05162660237533075)), (2982, np.float64(0.051571026011092896)), (3508, np.float64(0.05134100388583106)), (3362, np.float64(0.05129264264882042)), (3839, np.float64(0.05109471013398714)), (1407, np.float64(0.05102981160158165)), (704, np.float64(0.051010270316117774)), (2627, np.float64(0.050975278420821946)), (4327, np.float64(0.05091960386245153)), (142, np.float64(0.050908828034154086)), (2213, np.float64(0.05072154793641495)), (1643, np.float64(0.05067073347375055)), (1626, np.float64(0.05053178906558775)), (4403, np.float64(0.050429361015266794)), (3211, np.float64(0.050174411339723536)), (562, np.float64(0.05006069741594735)), (144, np.float64(0.049577350563376296)), (4351, np.float64(0.049418678731493026)), (2934, np.float64(0.04912295926145892)), (1689, np.float64(0.0490997774364937)), (4048, np.float64(0.04900259979464637)), (2197, np.float64(0.04899432620680649)), (824, np.float64(0.048299635189270884)), (3993, np.float64(0.048200824004280704)), (3769, np.float64(0.04818275055635343)), (1163, np.float64(0.04817935658450527)), (36, np.float64(0.04807054670939903)), (2321, np.float64(0.04790702925816181)), (1634, np.float64(0.04783588116347303)), (99, np.float64(0.047386401483155385)), (3754, np.float64(0.04734011003335122)), (2645, np.float64(0.04733292177025811)), (3957, np.float64(0.04720008833939813)), (1042, np.float64(0.04719065998587904)), (272, np.float64(0.047161792003036926)), (2017, np.float64(0.047029454893297254)), (3815, np.float64(0.046982421337882864)), (4097, np.float64(0.046945676271673384)), (2685, np.float64(0.04676745219812884)), (566, np.float64(0.04651601682603873)), (3099, np.float64(0.04640337458574713)), (2037, np.float64(0.04620635554126003)), (854, np.float64(0.04606131233370612)), (4067, np.float64(0.04596256561645201)), (3594, np.float64(0.04590039874037261)), (1420, np.float64(0.04589487416250288)), (3965, np.float64(0.04586003402403375)), (3391, np.float64(0.045543879624380716)), (109, np.float64(0.045514192029423486)), (4182, np.float64(0.04550523910016095)), (1852, np.float64(0.04544331798660274)), (1832, np.float64(0.04539436753065283)), (3595, np.float64(0.045136350461025265)), (2443, np.float64(0.04466329281529158)), (3597, np.float64(0.04448915697126423)), (1436, np.float64(0.04440473808253275)), (3959, np.float64(0.04439787284847897)), (2614, np.float64(0.04436319955185501)), (1858, np.float64(0.044271988418645616)), (486, np.float64(0.04425396842219426)), (3516, np.float64(0.04409248411215426)), (844, np.float64(0.044037830970810946)), (2158, np.float64(0.0435875238851951)), (2031, np.float64(0.043552932217288544)), (1985, np.float64(0.0435360783342429)), (1282, np.float64(0.043421153681258394)), (2739, np.float64(0.043419736419463104)), (1795, np.float64(0.043418999677423145)), (3823, np.float64(0.04332795123950078)), (1306, np.float64(0.04315762058102716)), (3407, np.float64(0.043131334260155)), (2170, np.float64(0.043094840850978096)), (790, np.float64(0.04307962742604932)), (481, np.float64(0.04302786585038039)), (2720, np.float64(0.04302557419559406)), (4233, np.float64(0.04301818617071798)), (770, np.float64(0.042563484039362644)), (2162, np.float64(0.04248862971084599)), (85, np.float64(0.0424725055428089)), (382, np.float64(0.042385100757096096)), (195, np.float64(0.04219540023652584)), (1339, np.float64(0.04205499504045141)), (2196, np.float64(0.04184046346807278)), (4616, np.float64(0.04175395751086475)), (4109, np.float64(0.04169665972753589)), (4178, np.float64(0.0415446362602051)), (874, np.float64(0.04150038134141262)), (2463, np.float64(0.04131998627263377)), (3182, np.float64(0.04129955383743511)), (3707, np.float64(0.04126275830348074)), (2246, np.float64(0.041230331128246575)), (543, np.float64(0.04120807947165839)), (2629, np.float64(0.041124697331249606)), (447, np.float64(0.0410837426656622)), (875, np.float64(0.041030270473964514)), (456, np.float64(0.040975622948447296)), (3466, np.float64(0.04092351026524507)), (1096, np.float64(0.040895638325521864)), (70, np.float64(0.040888532001355095)), (3127, np.float64(0.040651707148040214)), (205, np.float64(0.04061939150990062)), (3235, np.float64(0.04057632172562061)), (4054, np.float64(0.040359838715991574)), (3803, np.float64(0.040318795753118315)), (166, np.float64(0.040318247191175424)), (367, np.float64(0.04020408565923937)), (1707, np.float64(0.04010808307921237)), (1816, np.float64(0.040066031511665254)), (5, np.float64(0.039683304160885745)), (234, np.float64(0.03966081640421785)), (4557, np.float64(0.0396548964385874)), (3308, np.float64(0.03963485114076243)), (217, np.float64(0.039587299660039564)), (64, np.float64(0.03951170108697503)), (3076, np.float64(0.03950424157007609)), (4045, np.float64(0.03949432465275869)), (855, np.float64(0.039425284482693626)), (976, np.float64(0.03940230446151288)), (3524, np.float64(0.03938948043867126)), (3807, np.float64(0.03935812877078235)), (1005, np.float64(0.03920123714173172)), (1680, np.float64(0.0391295703855894)), (4053, np.float64(0.03909493770391259)), (4721, np.float64(0.038951661714637646)), (2924, np.float64(0.038826572700522255)), (2710, np.float64(0.03882296878047)), (1451, np.float64(0.03880110989523726)), (3320, np.float64(0.03879727130769625)), (1019, np.float64(0.038770599421298166)), (443, np.float64(0.03872257908920673)), (3408, np.float64(0.03871553384554565)), (157, np.float64(0.03861208957481922)), (2852, np.float64(0.03855912221379635)), (4369, np.float64(0.03851648891538558)), (1138, np.float64(0.038503122977667545)), (2218, np.float64(0.03838640990644041)), (3477, np.float64(0.03834999185625059)), (4653, np.float64(0.03826436602488043)), (1585, np.float64(0.03825480139941728)), (4663, np.float64(0.0382530659985477)), (1623, np.float64(0.03825123274873397)), (506, np.float64(0.03823036264704599)), (440, np.float64(0.038219921546274904)), (739, np.float64(0.03820217086332078)), (4684, np.float64(0.03814947688927337)), (4003, np.float64(0.03814174021258896)), (4379, np.float64(0.03810662165304876)), (3611, np.float64(0.03803926535181904)), (4028, np.float64(0.03803908148216563)), (1100, np.float64(0.03803492343022116)), (2264, np.float64(0.03802169083497799)), (1084, np.float64(0.03789645317025404)), (1296, np.float64(0.03787523198738658)), (2950, np.float64(0.037873832313917354)), (52, np.float64(0.03783042263675596)), (482, np.float64(0.03781369219772001)), (4699, np.float64(0.03777336097263112)), (751, np.float64(0.03776608220151378)), (935, np.float64(0.03770937948411045)), (3421, np.float64(0.0376571232205632)), (2675, np.float64(0.037613561514886255)), (633, np.float64(0.03758012011286105)), (4374, np.float64(0.03755717483119344)), (1594, np.float64(0.03748348505759661)), (420, np.float64(0.03743775784777107)), (408, np.float64(0.03740741449591359)), (2368, np.float64(0.03730158365443574)), (743, np.float64(0.03722754684327308)), (1509, np.float64(0.03713006835788132)), (2693, np.float64(0.03708246226943038)), (3797, np.float64(0.03704731091152294)), (1034, np.float64(0.037037330979782186)), (2280, np.float64(0.03703222219880967)), (749, np.float64(0.037020231034268304)), (967, np.float64(0.03696230392071568)), (2447, np.float64(0.036952816170768094)), (4173, np.float64(0.03694286532017995)), (613, np.float64(0.03684809705291817)), (3860, np.float64(0.036824905878708084)), (1107, np.float64(0.03681212304718691)), (3691, np.float64(0.03680105223178333)), (3109, np.float64(0.03677358854404714)), (2410, np.float64(0.036727085027893645)), (2908, np.float64(0.03668659084337712)), (3234, np.float64(0.03659404412570726)), (244, np.float64(0.03657120562028371)), (2022, np.float64(0.0365465959926886)), (325, np.float64(0.036546586905490654)), (4621, np.float64(0.03638164416611111)), (401, np.float64(0.03636568397049767)), (883, np.float64(0.03635946326320248)), (3889, np.float64(0.03630812689410745)), (3208, np.float64(0.036296712897038674)), (342, np.float64(0.03629116852548753)), (2057, np.float64(0.036254261280610135)), (2440, np.float64(0.03621572345031562)), (2998, np.float64(0.036178060741576604)), (4281, np.float64(0.036171723147262774)), (2477, np.float64(0.036171120530129296)), (4216, np.float64(0.03612760719566508)), (1694, np.float64(0.03606096782808935)), (1143, np.float64(0.036054241330740075)), (791, np.float64(0.0359651861837499)), (2077, np.float64(0.03596021676270367)), (395, np.float64(0.035919197640393044)), (3117, np.float64(0.035878244411303925)), (27, np.float64(0.03586735222811741)), (4486, np.float64(0.03586043160626086)), (1140, np.float64(0.03584641240415736)), (2931, np.float64(0.035790296457863996)), (2180, np.float64(0.03577509219553407)), (460, np.float64(0.03571399309907643)), (1324, np.float64(0.035711858974542286)), (307, np.float64(0.03570265592220216)), (4169, np.float64(0.035661915217594334)), (74, np.float64(0.03560576705270941)), (2496, np.float64(0.03559532182857264)), (2821, np.float64(0.035541198790793)), (4150, np.float64(0.0355262252326942)), (2096, np.float64(0.03550860692191753)), (4036, np.float64(0.03539798305297505)), (3406, np.float64(0.03533184288641267)), (3640, np.float64(0.03531737155536467)), (470, np.float64(0.0353094002889586)), (1920, np.float64(0.03519332310243699)), (830, np.float64(0.035192550548499534)), (2985, np.float64(0.03506303969541026)), (845, np.float64(0.035049053591273714)), (2118, np.float64(0.03504098270302351)), (968, np.float64(0.035033809603508596)), (3919, np.float64(0.03499729484217179)), (2040, np.float64(0.034985888599776034)), (204, np.float64(0.03497603590001751)), (2777, np.float64(0.03493458374498716)), (4089, np.float64(0.034858723292894994)), (34, np.float64(0.03483684662317486)), (2650, np.float64(0.034783403659217234)), (4262, np.float64(0.03475732893

In [33]:
print('Top 30 Movies Suggested for you: \n')

i = 1

for movie in Sorted_Similar_Movies:
    index = movie[0]
    title_from_index = df[df.index==index]['Movie_Title'].values[0]
    if (i<31):
        print(i, '.',title_from_index)
        i+=1

Top 30 Movies Suggested for you:

1 . City of God
2 . Night of the Living Dead
3 . Step Up 2: The Streets
4 . A Nightmare on Elm Street 3: Dream Warriors
5 . Two Evil Eyes
6 . The Family Man
7 . S.W.A.T.
8 . Tuck Everlasting
9 . Disturbing Behavior
10 . The Place Beyond the Pines
11 . Crash
12 . Salton Sea
13 . Masked and Anonymous
14 . ZMD: Zombies of Mass Destruction
15 . Closer
16 . Hollow Man
17 . Trash
18 . Get Rich or Die Tryin'
19 . Thirteen Conversations About One Thing
20 . Like Crazy
21 . Enemy of the State
22 . Chloe
23 . Down Terrace
24 . The Cry of the Owl
25 . Logan's Run
26 . Collateral Damage
27 . The Hurt Locker
28 . Bad Santa
29 . Body Double
30 . City By The Sea

Top 10 Movie Recommendation System

In [34]:
Movie_Name = input('Enter your favorite movie name: ')

list_of_all_titles = df['Movie_Title'].tolist()

Find_Close_Match = difflib.get_close_matches(Movie_Name, list_of_all_titles)

Close_Match = Find_Close_Match[0]

Index_of_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]

Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Movie]))

sorted_similar_movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)

print('Top 10 Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = df[df.Movie_ID==index]['Movie_Title'].values
    if (i<11):
        print(i,'.',title_from_index)
        i+=1

Enter your favorite movie name: Iron Man
Top 10 Movies suggested for you :

1 . ['Iron Man']
2 . ['The Mummy Returns']
3 . ['Fascination']
4 . ['Out Cold']
5 . ['Lethal Weapon 3']
6 . ['Robin and Marian']
7 . ['Hackers']
8 . ['Just My Luck']
9 . ['Snow White and the Huntsman']
10 . ['The Time Machine']